### ISSUE TITLE
Ubuntu 18 install instructions

### ISSUE THREAD

**Issue by pdales** [haikarainen/light#100]
After struggling to to get light to work without having to use sudo, here is the solution:
```
tar xf light-x.yy.tar.gz
cd light-x.yy/
./configure --with-udev=/lib/udev/rules.d && make
sudo make install
sudo usermod -a -G video $LOGNAME
```
Then I needed to restart my laptop for the permission changes to take effect. Perhaps you could update the install instructions with this information to help others.

**Comment by ivanhercaz** [comment]
@pdales, did you try to `make deb` the pre-built deb files as indicates the section "Debian/Ubuntu" in the README?

**Comment by pdales** [comment]
I tried downloading the deb, installing via gdebi, adding my username to
video group and restarting. Light worked but I still could not use without
sudo

**Comment by theholy7** [comment]
I just installed by downloading 1.2 .deb and also need to use `sudo`. I did `sudo chmod 4755 /usr/bin/light` and that seems to allow me to use `light -S 50` correctly.

**Comment by troglobit** [comment]
@theholy7 The .deb package installs udev rules to change the group of the files used in /sys to `video`.  If your user is member of that group (e.g. `adduser foo video`, followed by logout/login) then you don't need to use sudo och suid root.  This was once part of the documentation, maybe it's not there anymore.

Unfortunately I no longer have time (or interest) to work on this application, in part because I now have my own little tool to do what I need.  So I won't do any more updates of the .deb package. Thanks

**Comment by theholy7** [comment]
@troglobit no worries, I just messaged hwere so that people know how I solved it. Clearly i failed to read something! I really like the tool :)
