### ISSUE TITLE
Only working with sudo (even with video group)

### ISSUE THREAD

**Issue by aDogCalledSpot** [haikarainen/light#112]
I'm using the latest .deb on Ubuntu 18.04 on a Lenovo T460p.

Everything works fine with sudo but without I get the following message:

```
light -v 3 -U 5
helpers.c:21: Error: could not open '/home/ari/.config//light/targets/sysfs/backlight/auto/minimum' for reading
helpers.c:21: Error: Verify it exists with the right permissions
helpers.c:45: Error: could not open '/sys/class/backlight/intel_backlight/brightness' for writing
helpers.c:45: Error: Verify it exists with the right permissions
impl/sysfs.c:133: Error: failed to write to sysfs device
light.c:905: Error: failed to write to target
main.c:20: Error: Execution failed
```

I'm added to the video group and the udev rules appear to be placed correctly.

**Comment by haikarainen** [comment]
Verify your udev rules by manually writing to the controller, if that fails, the problem is not an application issue. If you can write to the controller manually using the same account that youre invoking light with, reopen this issue.

Sorry but I get a ton of permission issues on this repo that frankly has got nothing to do with light itself.

**Comment by streetturtle** [comment]
Here is how to fix the permission issues: https://github.com/haikarainen/light/issues/113#issuecomment-632638436
