### ISSUE TITLE
Don't install as SUID executable

### ISSUE THREAD

**Issue by mkoskar** [haikarainen/light#12]
Rather than installing `light` as SUID executable, distribute it with following `udev` rule or manual post-installation step expected to be done by user.

```
==> /etc/udev/rules.d/90-backlight.rules <==
ACTION=="add", SUBSYSTEM=="backlight", RUN+="/bin/chgrp video /sys/class/backlight/%k/brightness"
ACTION=="add", SUBSYSTEM=="backlight", RUN+="/bin/chmod g+w /sys/class/backlight/%k/brightness"
```

If installed by package it could go to `/usr/lib/udev/rules.d/90-backlight.rules`.

**Comment by haikarainen** [comment]
I was in a discussion about this a very long time ago (I think 4 years ago). Back then, from what I can remember, udev rules was very messy, but I honestly do not remember the exact reason I went with suid instead of udev. 

Right now though, I can say that light have always had focus on very low-level functionality. It already bypasses a lot of recommended stuff and directly accesses sysfs, which is why it tends to be so robust and work in so many environments in the first place. Introducing udev as a dependency would hurt this software "philosophy", even if by a little.

I might add it as an alternative install step though.

**Comment by mkoskar** [comment]
Well, using `sysfs` ACPI interface is pretty standard way of changing backlight, so I don't know what you mean by "bypasses a lot of recommended stuff". For one I was doing same for years in bash script. Just discovered this software because I wanted to make it nicer with percentages and was about to rewrite bash but thought I better look, somebody already had to write some nicer interface :). I don't like SUID executables for obvious reasons but I understand your points. I'll try to raise this with `systemd` so it might get configured by default.
