### ISSUE TITLE
Set minimum brightness is off by 0.01 or 0.02 for some values

### ISSUE THREAD

**Issue by KeaganBailey** [haikarainen/light#140]
I'm unsure of what the pattern is, but some minimum brightness values are reduced by 0.01 or 0.02, while other values such as 11 are unaffected

Also  setting the minimum value to 10.02 results in "10.01", but setting the minimum to 10.01 results in "9.99"

`~ > light -N 10.02`
`~ > light -P`      
`10.01`
`~ > light -N 10.01`
`~ > light -P`
`9.99`
`~ > light -N 10`
`> light -P`
`9.99`

`~ > light -N 11`
`~ > light -P`
`11.00`
`~ > light -N 11.5`
`~ > light -P`     
`11.49`

Quick edit: I also want to add these results are reflected when using `light -U 10`, when `light -N 10` is set -U will reduce the brightness from 100.00 to 10.00, then when the command is used once more it will reduce the brightness to 9.99

**Comment by haikarainen** [comment]
The values are written to a controller in the end, that has a resolution. Say it can go from 0-1023 for example. But the interface that we use is in percentage (0-100). So say you want to set 10 percent, that’s 102,3. But that’s not an integer, so it’s floored to 102 and set like that. So when you read the percentage, it’s now 9,9% instead of 10%

It all depends on the controller resolution.
