### ISSUE TITLE
Great package!

### ISSUE THREAD

**Issue by koesherbacon** [haikarainen/light#20]
Not an issue, but since there's nowhere else to contact you on GitHub, I'm writng this here.  Your 'Light' package is great!  Kudos, dude.  Keep it up :+1: :)

**Comment by haikarainen** [comment]
Thanks man! :) very appreciated!

**Comment by azzamsa** [comment]
@haikarainen Hi.

Thank you so much for this package. I use it almost half year. I use
it multiple times daily. To adjust screen when meeting, presenting,
and other things.

I'm really happy with this package. I almost desperate cause
`xbacklight` and other method mentioned in internet doesn't work to
adjust my screen brightness. It almost impossible to use machine with
extremely high brightness all day long. Then I find `light` in search
engine result. `Light` saved my life!.

Before `light`. We use `redshift` to trick our screen brightness. No
other solution for us. Now we tell each other to try `light`.

Thanks a ton.

**Comment by haikarainen** [comment]
@azzamsa that just warms my heart! Thank you!

**Comment by azzamsa** [comment]
@haikarainen I am forget something to mention, Just back to my laptop :)

Would you like to add some summary/explanation on how does `light` works?. It will feed people curiosity on why other method/app failed but `light` shines.

**Comment by haikarainen** [comment]
@azzamsa it accesses the backlight drivers directly via sysfs instead of some other route. 

Im not sure but I think xbacklight and likewise uses other libraries on top of that to do their bidding, which for some reason doesnt support all installed backlight drivers.  Ive also heard that light doesnt operate in the "correct" or "recommended" fashion, but it provides much wider support so I havent altered it.

**Comment by azzamsa** [comment]
> it accesses the backlight drivers directly via sysfs instead of some other route.

Oh, this is the main difference

> Im not sure but I think xbacklight and likewise uses other libraries on top of that to do their bidding, which for some reason doesn't support all installed backlight drivers

Sure. Some laptops here doens't work with xbacklight. But works with light.

> Ive also heard that light doesn't operate in the "correct" or "recommended" fashion, but it provides much wider support so I haven't altered it.

I love the principle of "Ideally, something simple that works." :).
Even I still don't have any issue of "incorrect" way light that affect bad things on other package. 

I mention light on my setup installation method. Maybe one day I will give this separate mention. I believe this package should have wider attention.

**Comment by AloisMahdal** [comment]
OK, since we already have this "OT" ticket... :-D I third that!

A long, long time ago, <strike>in a galaxy far far away,</strike> I used to have issues with setting light properly.  That was when I did not have `/usr/bin/light`.  Now, about a year later, I hardly even remember what kind of problems I used to have.  What I do know is that I have light in my dmenu in my bmo in my i3 in my debian/fedora, it's shared between 3 machines and it just works.

This is package is an example of UNIX philosophy at its best.  Thanks for the `light`!
