### ISSUE TITLE
Could not get min brightness on linux 4.11

### ISSUE THREAD

**Issue by Anthony25** [haikarainen/light#22]
Hello,
Since linux 4.11, on ArchLinux, light keeps failing when getting or setting the backlight:

```
$ light -S 40 -v 3
Automatic mode -- finding best controller.
/sys/class/backlight/intel_backlight/brightness.
/sys/class/backlight/intel_backlight/brightness.
/sys/class/backlight/intel_backlight/brightness.
error: "file contents are corrupt", in "src/helpers.c" on line 74.
error: "could not read minimum cap from file", in "src/light.c" on line 797.
error: "could not get min brightness", in "src/light.c" on line 346.
error: "Execution failed", in "src/main.c" on line 19.
```

It seems that the min_backlight file has been removed from `/sys/class/backlight/intel_backlight`:

```
$ ls -al /sys/class/backlight/intel_backlight/ 
total 0
drwxr-xr-x 3 root root     0 24 mai   14:04 .
drwxr-xr-x 6 root root     0 24 mai   14:04 ..
-r--r--r-- 1 root root  4,0K 24 mai   14:20 actual_brightness
-rw-r--r-- 1 root root  4,0K 24 mai   14:20 bl_power
-rw-rw-r-- 1 root video 4,0K  7 juin  13:46 brightness
lrwxrwxrwx 1 root root     0 24 mai   14:20 device -> ../../card0-eDP-1
-r--r--r-- 1 root root  4,0K 24 mai   14:20 max_brightness
drwxr-xr-x 2 root root     0  7 juin  13:40 power
lrwxrwxrwx 1 root root     0 31 mai   10:10 subsystem -> ../../../../../../../class/backlight
-r--r--r-- 1 root root  4,0K 24 mai   14:20 type
-rw-r--r-- 1 root root  4,0K 24 mai   14:20 uevent
```

I'm using the `light-git` package, and have a xps 9560 (Skylake CPU).
Thanks!

**Comment by haikarainen** [comment]
Yeah, same here apparently! I'll make it default to 0 if the file isn't available.

Thanks a ton, and nice catch!

**Comment by haikarainen** [comment]
Please post the contents of `/etc/light/mincap/intel_backlight`

The minimum brightness is not part of the controller, but of light itself.

**Comment by haikarainen** [comment]
Also, try to run this command and see if it fixes it: `light -Sc 0` . It should write to the file mentioned in my previous comment, and make it proper.

**Comment by Anthony25** [comment]
Many thanks! `/etc/light/mincap/intel_backlight` was empty, so I tried to delete it, ran `light -Sc 0`, and now everything is working great!

**Comment by jplatte** [comment]
This also happened to me and was quite hard to debug. I was able to get it working again by writing to `/etc/light/mincap/intel_backlight` directly. Running `light -Sc 0` instead didn't work, and actually still doesn't work after everything else works again. Here is the output with that and `-v 3`:

```
Automatic mode -- finding best controller.
/etc/light/mincap/intel_backlight.
error: "could not open file for reading", in "src/helpers.c" on line 68.
error: "could not read value from brightness file", in "src/light.c" on line 581.
intel_backlight.
warning: "could not read controllers brightness file, so controller is not accessible", in "src/light.c" on line 657.
warning: "controller not accessible", in "src/light.c" on line 753.
error: "could not find an accessible controller", in "src/light.c" on line 762.
error: "could not find suitable controller", in "src/light.c" on line 272.
error: "Initialization failed", in "src/main.c" on line 13.
```

Also, even ignoring that `light -Sc` doesn't work for me, could you consider re-opening this issue until `light` can actually handle an empty file in `/etc/light/mincap`? It's definitely not linux 4.11 that causes this to happen, because for me it happened two days ago, and I have installed linux 4.11 since more than a month (plus I reboot regularily even outside kernel updates). I'm pretty sure it broke when I was playing around with light, passing it some potentially nonsense command combinations. I'll try to reproduce it.
