### ISSUE TITLE
Support external displays (e.g. Dell UP2516D)?

### ISSUE THREAD

**Issue by JanKoppe** [haikarainen/light#32]
Hello,

would you think supporting external displays is in scope? I'm talking about modern displays that expose some control interface via their USB port. My Dell UP2516D does so and Dell provides a cross platform SDK for just this purpose. [1]

Not sure how many backends you would want to support, or if you even want to extend this project at all, just asking before I start to sink time on a possible PR. :)

Regards

[1]: http://www.dell.com/support/home/de/de/debsdt1/drivers/driversdetails?driverId=JFHNP

**Comment by haikarainen** [comment]
Yes, it is definitely in scope for the project. However I do not really have much time for this project anymore. I'd recommend you create a pull request.

Since there is a possibility of multiple different backends for this, I highly recommend creating an abstract interface that can tie them all together, and maybe a plugin system that extends functionality to support different backends. That way, we could also make sure to license things correctly, should DELL or likewise demand it.

**Comment by haikarainen** [comment]
@Jankoppe Changes has been merged to easily allow for such an implementation. Please read DOCUMENTATION.md for details on how to implement it!

**Comment by haikarainen** [comment]
I've taken a look at the API, and I have a small suspicion that it may be possible that the driver already exposes stuff somewhere under the sysfs (at `/sys`) . It would make it much more feasible to implement support for it in light, so I urge you to investigate it!
