### ISSUE TITLE
Commands require sudo to use

### ISSUE THREAD

**Issue by btamas97** [haikarainen/light#35]
When i tried to use light seemingly nothing happened, however when i used it with sudo it worked just fine, so i turned on the warning and error messages to see what's going on. I got the following messages:

`[dreamer@localhost ~]$ light -A 5 -v 3
Automatic mode -- finding best controller.
warning: "could not open controller brightness file for writing, so controller is not accessible", in "src/light.c" on line 648.
warning: "controller not accessible", in "src/light.c" on line 722.
error: "could not find an accessible controller", in "src/light.c" on line 731.
error: "could not find suitable controller", in "src/light.c" on line 268.
error: "Initialization failed", in "src/main.c" on line 13.
[dreamer@localhost ~]$ sudo light -A 5 -v 3
[sudo] dreamer jelszava: 
Automatic mode -- finding best controller.
`

I'm pretty much a linux newbie so it's comepletely possible that i didn't configure something what i should have. I just installed the community package provided by FrostyX. Also i'm suspecting permission problems.

**Comment by FrostyX** [comment]
> I just installed the community package provided by FrostyX

Since nobody knows me here, I should probably specify, that I am the maintainer of `light` package in Fedora. We have 1.0 version there.
https://apps.fedoraproject.org/packages/light/overview/

**Comment by btamas97** [comment]
Removed the other and installed this package. The problem remained the same.

**Comment by haikarainen** [comment]
Sounds like a possible packaging problem? I havent used Linux in ages so I cant test it atm :/ 

However, from the readme file: 

Optional: If you want to use udev rules instead of suid to manage sysfs permissions, you may skip the make install step and instead add something like the following to /etc/udev/rules.d/90-backlight.rules after copying your binaries:

    ACTION=="add", SUBSYSTEM=="backlight", RUN+="/bin/chgrp video /sys/class/backlight/%k/brightness"
    ACTION=="add", SUBSYSTEM=="backlight", RUN+="/bin/chmod g+w /sys/class/backlight/%k/brightness"

**Comment by FrostyX** [comment]
@haikarainen, version 1.0 worked for me without sudo, but now I am trying version 1.1 and I get

    [jkadlcik@chromie light]$ light -U 5 -v3 
    notice: "Automatic mode -- finding best controller", in "src/light.c" on line 329.
    notice: "found 'intel_backlight' controller", in "src/light.c" on line 885.
    warning: "could not open '/sys/class/backlight/intel_backlight/brightness' for writing", in "src/helpers.c" on line 189.
    warning: "check if this file exists or if you have the right permissions", in "src/helpers.c" on line 189.
    warning: "could not open controller brightness file for writing, so controller is not accessible", in "src/light.c" on line 787.
    warning: "controller not accessible", in "src/light.c" on line 906.
    error: "could not find an accessible controller", in "src/light.c" on line 914.
    error: "could not find suitable controller", in "src/light.c" on line 332.
    error: "Initialization failed", in "src/main.c" on line 13.

when running the command with sudo, I also get some warnings

    [jkadlcik@chromie light]$ sudo light -U 5 -v3 
    notice: "Automatic mode -- finding best controller", in "src/light.c" on line 329.
    notice: "found 'intel_backlight' controller", in "src/light.c" on line 885.
    warning: "could not open '/etc/light/mincap/intel_backlight' for reading", in "src/helpers.c" on line 203.
    warning: "check if this file exists or if you have the right permissions", in "src/helpers.c" on line 203.
    notice: "cap file doesn't exist or can't read from it, so assuming a minimum brightness of 0", in "src/light.c" on line 943.
    notice: "executing light on 'intel_backlight' controller", in "src/light.c" on line 439.
    notice: "setting brightness 725 (raw) to controller", in "src/light.c" on line 744.

but the brightness is correctly set.

**Comment by haikarainen** [comment]
Can you orphan github projects? lol. I've been trying to get someone else to adopt this project for some time now. I sadly dont have time to keep it afloat, and at some point I kinda got someone else to maintain it, however he seems to have also lost interest.

I hate this project. It started off pretty decently but today its just messy, and I honestly dont have a good overview of the code anymore.  There has been some code written by others that are in the master (and 1.1) that I havent reviewed as well as I maybe should have.  

If you know C, feel free to grab a shovel and dig in. The codebase is very small, and not that complicated. Otherwise, I'll might look into it when I feel like I have time to spend on it. 

Also, make sure its not a packaging error @FrostyX . Proper permissions need to be set and maintained (via udevrules orlikewise).

**Comment by FrostyX** [comment]
> Can you orphan github projects? lol. I've been trying to get someone else to adopt this project for some time now.

I get it, a person has a problem, creates a nice tool to fix it, then moves on, the original problem is not there anymore and so there isn't a motivation to develop the tool anymore. Unfortunately, I don't know C, so I can't continue the project. But know that this is an awesome project which saved my !@#$. And according to people commenting my blog post, theirs too.

Back to the original issue, it turns out that it might be a packaging issue. I am sorry, that we spammed upstream with it. This 

    - install -m755 ./light %{buildroot}/%{_bindir}/
    + install -m4755 ./light %{buildroot}/%{_bindir}/   

seems to fixed it. I don't know why the old version worked without it and the new one doesn't, but it is probably not that important.

@btamas97 can you please try whether it fixes also your issue? I've prepared a build in Copr and also in koji.

**Comment by haikarainen** [comment]
@FrostyX  Very glad to hear that it was an easy fix! Thanks a ton for your contribution!

**Comment by btamas97** [comment]
Thank you @FrostyX it works perfectly now!

**Comment by troglobit** [comment]
So hi, I'm the new co-maintainer :wave: 

Suid root binary isn't optimal, but the udev rules are a bit better.  We've got suggestions for using Policy Kit, which I've never used myself before, so maybe someone can have a go at it and post a pull request?

Meanwhile, closing this issue since the problem was resolved.
