### ISSUE TITLE
Old? content in github releases .tar.gz

### ISSUE THREAD

**Issue by AloisMahdal** [haikarainen/light#49]
I'm trying to follow README.md and download tarball from GitHub releases page, but these don't contain neither ./configure nor ./autogen.sh:

    $ tar -tf light-1.1.2.tar.gz 
    light-1.1.2/
    light-1.1.2/.gitignore
    light-1.1.2/CHANGELOG
    light-1.1.2/LICENSE
    light-1.1.2/Makefile
    light-1.1.2/README.md
    light-1.1.2/include/
    light-1.1.2/include/helpers.h
    light-1.1.2/include/light.h
    light-1.1.2/makeexec.sh
    light-1.1.2/src/
    light-1.1.2/src/helpers.c
    light-1.1.2/src/light.c
    light-1.1.2/src/main.c

I'm not sure if I'm not missing anything.  The README.md in the tarball is older form and has copyright up to 2014, so it looks like the content is actually from other release.

(By the way, the release naming format has changed from `v1.0` to `1.1`, perhaps this could have broken some release scrirpt?)

**Comment by troglobit** [comment]
The README of each tarball matches that release, so to build that release please follow the instructions of that README.

To build the latest, yet unreleased version, follow the instructions of that README.  

I.e., for the (yet unreleased) v1.2 follow the instructions in that README (run `autogen.sh` for the latest GIT revision) and for released versions <v1.2 , please follow the README of that version.

In the v1.2 release cycle we've introduced a configure script (which with all generated files will be included in an official released tarball), but official released (tagged) tarballs (or zip files) before that contain a regular Makefile.  The GIT master branch tracks the latest (possibly unreleased) sources.

I'm personally not familiar with any changes between v1.0 and v1.1, since I stepped in just now prior to the v1.2 release.  The changes we've made on the latest GIT master are only pertinent to the upcoming v1.2.  I hope this answers your question, if so please affirm and close or compliment this issue request.

**Comment by AloisMahdal** [comment]
Thanks for explanation; looks like I got confused.

FYI; I'm preparing .spec file for my [Fedora COPR build][fcopr]; later I'd like to add it to Fedora and maintain it there.

  [fcopr]: https://copr.fedorainfracloud.org/coprs/netvor/light/

**Comment by AloisMahdal** [comment]
> ... later I'd like to add it to Fedora and maintain it there.

Oh, I see now @FrostyX was faster...

**Comment by troglobit** [comment]
@AloisMahdal I'll be releasing the latest GIT as v1.2 soon, a couple of weeks, hang in there.

**Comment by FrostyX** [comment]
> FYI; I'm preparing .spec file for my Fedora COPR build; later I'd like to add it to Fedora and maintain it there.
> Oh, I see now @FrostyX was faster...

@AloisMahdal I've sent you an email regarding co-maintenance of `light` package in Fedora. Let's discuss it there.
