### ISSUE TITLE
Deb packages links are broken

### ISSUE THREAD

**Issue by tundo91** [haikarainen/light#6]
http://haikarainen.1.ai/light/light_0.9-1_i386.deb

**Comment by haikarainen** [comment]
Oh crap, completely missed this (usually get notifications through email but not this time). 

Replace the domain name with www.fredrikhaikarainen.se and it should work

http://www.fredrikhaikarainen.se/light/light_0.9-1_i386.deb

Thank you for contributing!

**Comment by tundo91** [comment]
thanks dude!

**Comment by tristan-k** [comment]
The links are broken again.

**Comment by MeanEYE** [comment]
Give me a moment.

**Comment by MeanEYE** [comment]
Can you be specific which links are broken?

**Comment by MeanEYE** [comment]
Sorry for the retarded comments. I assumed it was my project as I had similar issues with RPM packages. :)

**Comment by haikarainen** [comment]
@MeanEYE Not sure what you're referring to, but it's OK, we are all retarded sometimes!

@tristan-k Yeah sorry they are, and have been for a long time :-1:  I dont know about a github release function but I will read up on it. I'm not sure when I will repackage these .debs though, all my source files for them are since long gone.

Very sorry for this issue, I understand that it must be very frustrating.

 I'm re-opening this issue until it has been solved.

**Comment by MeanEYE** [comment]
@haikarainen I removed my comments fast so maybe you didn't get emails. :)
